In [7]:
from caffe2.python import workspace, model_helper
from caffe2.python import core, schema
import numpy as np

# Three ways to use operators

In [12]:
workspace.ResetWorkspace()
workspace.FeedBlob('a', np.array([0, 1, 2]))
m = model_helper.ModelHelper('my_net')
m.net.Concat(['a', 'a'], ['concat', 'concat_split'], axis=0, add_axis=1)
workspace.RunNetOnce(m.net)
workspace.FetchBlobs(workspace.Blobs())

[array([0, 1, 2], dtype=int64), array([[0, 1, 2],
        [0, 1, 2]], dtype=int64), array([1, 1], dtype=int32)]

In [15]:
workspace.ResetWorkspace()
op = core.CreateOperator(
    "Concat",
    ["X1",  "X2"],
    ["Y", "split_info"],
    axis=0, 
    add_axis=1
)
workspace.FeedBlob("X1", np.array([0, 1, 2]))
workspace.FeedBlob("X2", np.array([0, 1, 2]))
workspace.RunOperatorOnce(op)
workspace.FetchBlobs(workspace.Blobs())

[array([0, 1, 2], dtype=int64),
 array([0, 1, 2], dtype=int64),
 array([[0, 1, 2],
        [0, 1, 2]], dtype=int64),
 array([1, 1], dtype=int32)]

In [16]:
workspace.ResetWorkspace()
net = core.Net('my_net')
workspace.FeedBlob('a', np.array([0, 1, 2]))
net.Concat(['a', 'a'], ['concat', 'split'], axis=0, add_axis=1)
workspace.RunNetOnce(m.net)
workspace.FetchBlobs(workspace.Blobs())

[array([0, 1, 2], dtype=int64), array([[0, 1, 2],
        [0, 1, 2]], dtype=int64), array([1, 1], dtype=int32)]